// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task.Context;

#nullable disable

namespace task.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20240404065734_depo")]
    partial class depo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task.Models.BusinessPartner", b =>
                {
                    b.Property<string>("linerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("linerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("linerId");

                    b.ToTable("BusinessPartner");
                });

            modelBuilder.Entity("task.Models.DepotDetail", b =>
                {
                    b.Property<string>("depotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("depotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("depotId");

                    b.ToTable("DepotDetail");
                });

            modelBuilder.Entity("task.Models.EquipmentDetails", b =>
                {
                    b.Property<int>("equipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("equipmentId"));

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ReferenceNo");

                    b.Property<string>("conTrackingNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("conTrackingNo");

                    b.Property<string>("depotId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("depotId");

                    b.Property<string>("equipmentLinerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("equipmentLinerId");

                    b.Property<string>("equipmentNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("equipmentNo");

                    b.Property<int>("equipmentSize")
                        .HasColumnType("int")
                        .HasColumnName("equipmentSize");

                    b.Property<DateTime>("gateInDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("gateInDateTime");

                    b.HasKey("equipmentId");

                    b.ToTable("EquipmentDetails");
                });

            modelBuilder.Entity("task.Models.transportDetail", b =>
                {
                    b.Property<int>("transportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transportId"));

                    b.Property<string>("driverEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("driverEmail");

                    b.Property<int>("driverMobileNo")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("driverMobileNo");

                    b.Property<string>("driverName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("driverName");

                    b.Property<string>("licenseNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("licenseNo");

                    b.Property<string>("transportCompany")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transportCompany");

                    b.HasKey("transportId");

                    b.ToTable("transportDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
